version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@1.0.0
  node: circleci/node@5.2.0
  nx: nrwl/nx@1.6.2

jobs:
  generate-config:
    executor: continuation/default
    resource_class: small
    steps:
      - checkout
      - nx/set-shas
      - node/install:
          node-version: 20.11.1
      - node/install-packages:
          override-ci-command: npm ci && npx -y clean-modules -y
      - run:
          name: Generate config
          command: |
            bash ./.circleci/generate-config.sh
      - continuation/continue:
          configuration_path: .circleci/generated-config.yml

workflows:
  setup:
    jobs:
      - generate-config
