version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@1.0.0
  node: circleci/node@5.2.0
  nx: nrwl/nx@1.6.2

jobs:
  generate-config:
    executor: continuation/default
    resource_class: small
    steps:
      - checkout
      - node/install:
          node-version: 22.1.0
      - node/install-packages:
          override-ci-command: npm ci && npx -y clean-modules -y
      - when:
          condition:
              equal: [ master, << pipeline.git.branch >> ]
          steps:
            - nx/set-shas:
                main-branch-name: master
                workflow-name: build_lint_test
      - when:
          condition:
              not:
                  equal: [ master, << pipeline.git.branch >> ]
          steps:
            - nx/set-shas:
                main-branch-name: develop
                workflow-name: build_lint_test
      - run:
          name: Generate config
          command: |
            bash ./.circleci/generate-config.sh
      - continuation/continue:
          configuration_path: .circleci/generated-config.yml

workflows:
  setup:
    jobs:
      - generate-config
